[github_app]
pr_commands = ["/review"]

[pr_reviewer]
extra_instructions = """
- Ensure code follows the project's coding standards.
- Verify that all new functions have corresponding unit tests.
- Check for clear and concise documentation in code comments.
"""
persistent_comment = true
final_update_message = true
require_pr_description = true
minimum_approvals = 2
[pr_description] # /describe #
generate_ai_title=true

[auto_best_practices]
enable_auto_best_practices = true # public - general flag to disable all auto best practices usage
utilize_auto_best_practices = true # public - disable usage of auto best practices in the 'improve' tool
extra_instructions = "" # public - extra instructions to the auto best practices generation prompt
content = ""
max_patterns = 5 # max number of patterns to be detected


[azure_devops_server]
pr_commands = [
    "/describe",
    "/review",
    "/improve",
]
